[build]
  publish = "public"
  command = "echo 'No build required'"

[functions]
  directory = "functions"

[[redirects]]
  from = "/socket.io/*"
  to = "https://slither-game-backend.web.app/socket.io/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 